### ISSUE TITLE
ACRE on Server not Fully Working

### ISSUE THREAD

**Issue by SepRex** [a3g/a3g-information#13]
Hi,

I'm playing with a group right now which has recently switched to ACRE2 rather than using Task Force Radio. Tonight was our second mission with it but we seem to be having problems.

Sometimes, for some players, the radios decide to cut in/out or make the radios unable to receive/transmit. I know that ACRE is a bit more realistic with the terrain/buildings than TFR though in one instance I was transmitting over the Medic Frequency to someone, while my Squad Leader couldn't contact the squad leader on the same hill.

There was direct line of sight and it was about 400metres using 152s, this kind of random cutting out has happened several times in the last two missions we've done. I remember back on Arma 2 there used to be a specific way Teamspeak channels had to be set up to help ACRE work but I'm not entirely sure what it was.

If any help/suggestions could be offered, it'd be much appreciated.

**Comment by BaerMitUmlaut** [comment]
http://slackin.idi-systems.com:3000/
